-- MEN DATA *****************************
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (1, 'Zara Casual Shirt 1', 'MEN', 'MEN', 'NAVY', 'SIZE_40', 2395.00, 2083.65, 'ZARA', 'img/casual1.jpg', 'Zara India', 'Premium quality and comfortable fit.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (2, 'Zara Casual Shirt 2', 'MEN', 'MEN', 'WHITE', 'SIZE_32', 1672.00, 1320.88, 'ZARA', 'img/casual2.jpg', 'Zara India', 'Durable, lightweight, and perfect for all-day wear.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (3, 'Zara Casual Shirt 3', 'MEN', 'MEN', 'RED', 'SIZE_32', 2805.00, 2159.85, 'ZARA', 'img/casual3.jpg', 'Zara India', 'Trendy design with breathable fabric.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (4, 'Zara Casual Shirt 4', 'MEN', 'MEN', 'BLUE', 'SIZE_30', 1422.00, 1094.94, 'ZARA', 'img/casual4.jpg', 'Zara India', 'Trendy design with breathable fabric.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (5, 'Zara Casual Shirt 5', 'MEN', 'MEN', 'BROWN', 'SIZE_40', 2555.00, 2069.55, 'ZARA', 'img/casual5.jpg', 'Zara India', 'Crafted with precision and stylish appeal.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (6, 'Zara Casual Shirt 6', 'MEN', 'MEN', 'BLACK', 'SIZE_44', 2014.00, 1409.80, 'ZARA', 'img/casual6.jpg', 'Zara India', 'Crafted with precision and stylish appeal.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (7, 'Zara Casual Shirt 7', 'MEN', 'MEN', 'BLACK', 'SIZE_30', 2618.00, 2277.66, 'ZARA', 'img/casual7.jpg', 'Zara India', 'Crafted with precision and stylish appeal.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (8, 'Zara Casual Shirt 8', 'MEN', 'MEN', 'GREEN', 'SIZE_34', 1087.00, 815.25, 'ZARA', 'img/casual8.jpg', 'Zara India', 'Trendy design with breathable fabric.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (9, 'Zara Casual Shirt 9', 'MEN', 'MEN', 'RED', 'SIZE_38', 2978.00, 2501.52, 'ZARA', 'img/casual9.jpg', 'Zara India', 'Premium quality and comfortable fit.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (10, 'Zara Casual Shirt 10', 'MEN', 'MEN', 'RED', 'SIZE_34', 2107.00, 1769.88, 'ZARA', 'img/casual10.jpg', 'Zara India', 'Premium quality and comfortable fit.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (11, 'H&M Formal Shirt 1', 'MEN', 'MEN', 'WHITE', 'SIZE_36', 1165.00, 920.35, 'H&M', 'img/formal1.jpg', 'H&M India', 'Premium quality and comfortable fit.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (12, 'H&M Formal Shirt 2', 'MEN', 'MEN', 'YELLOW', 'SIZE_30', 1341.00, 965.52, 'H&M', 'img/formal2.jpg', 'H&M India', 'Durable, lightweight, and perfect for all-day wear.', 3.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (13, 'H&M Formal Shirt 3', 'MEN', 'MEN', 'BROWN', 'SIZE_38', 1408.00, 1210.88, 'H&M', 'img/formal3.jpg', 'H&M India', 'Crafted with precision and stylish appeal.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (14, 'H&M Formal Shirt 4', 'MEN', 'MEN', 'NAVY', 'SIZE_38', 1548.00, 1269.36, 'H&M', 'img/formal4.jpg', 'H&M India', 'Trendy design with breathable fabric.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (15, 'H&M Formal Shirt 5', 'MEN', 'MEN', 'RED', 'SIZE_36', 1868.00, 1643.84, 'H&M', 'img/formal5.jpg', 'H&M India', 'Crafted with precision and stylish appeal.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (16, 'H&M Formal Shirt 6', 'MEN', 'MEN', 'BROWN', 'SIZE_34', 1139.00, 899.81, 'H&M', 'img/formal6.jpg', 'H&M India', 'Premium quality and comfortable fit.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (17, 'H&M Formal Shirt 7', 'MEN', 'MEN', 'GREY', 'SIZE_34', 2789.00, 2314.87, 'H&M', 'img/formal7.jpg', 'H&M India', 'Durable, lightweight, and perfect for all-day wear.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (18, 'H&M Formal Shirt 8', 'MEN', 'MEN', 'BLUE', 'SIZE_42', 1559.00, 1356.33, 'H&M', 'img/formal8.jpg', 'H&M India', 'Premium quality and comfortable fit.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (19, 'H&M Formal Shirt 9', 'MEN', 'MEN', 'BLUE', 'SIZE_36', 1228.00, 1080.64, 'H&M', 'img/formal9.jpg', 'H&M India', 'Premium quality and comfortable fit.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (20, 'H&M Formal Shirt 10', 'MEN', 'MEN', 'WHITE', 'SIZE_38', 1681.00, 1294.37, 'H&M', 'img/formal10.jpg', 'H&M India', 'Trendy design with breathable fabric.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (21, 'Nike T-Shirt 1', 'MEN', 'MEN', 'GREEN', 'SIZE_32', 1769.00, 1273.68, 'NIKE', 'img/tshirt1.jpg', 'Nike India', 'Durable, lightweight, and perfect for all-day wear.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (22, 'Nike T-Shirt 2', 'MEN', 'MEN', 'RED', 'SIZE_44', 1458.00, 1195.56, 'NIKE', 'img/tshirt2.jpg', 'Nike India', 'Durable, lightweight, and perfect for all-day wear.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (23, 'Nike T-Shirt 3', 'MEN', 'MEN', 'NAVY', 'SIZE_30', 2864.00, 2463.04, 'NIKE', 'img/tshirt3.jpg', 'Nike India', 'Durable, lightweight, and perfect for all-day wear.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (24, 'Nike T-Shirt 4', 'MEN', 'MEN', 'WHITE', 'SIZE_30', 2690.00, 2259.60, 'NIKE', 'img/tshirt4.jpg', 'Nike India', 'Premium quality and comfortable fit.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (25, 'Nike T-Shirt 5', 'MEN', 'MEN', 'MAROON', 'SIZE_34', 1265.00, 923.45, 'NIKE', 'img/tshirt5.jpg', 'Nike India', 'Perfect for casual and semi-formal wear.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (26, 'Nike T-Shirt 6', 'MEN', 'MEN', 'RED', 'SIZE_36', 2236.00, 1721.72, 'NIKE', 'img/tshirt6.jpg', 'Nike India', 'Perfect for casual and semi-formal wear.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (27, 'Nike T-Shirt 7', 'MEN', 'MEN', 'BLACK', 'SIZE_42', 1698.00, 1409.34, 'NIKE', 'img/tshirt7.jpg', 'Nike India', 'Crafted with precision and stylish appeal.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (28, 'Nike T-Shirt 8', 'MEN', 'MEN', 'GREY', 'SIZE_40', 2656.00, 1912.32, 'NIKE', 'img/tshirt8.jpg', 'Nike India', 'Trendy design with breathable fabric.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (29, 'Nike T-Shirt 9', 'MEN', 'MEN', 'MAROON', 'SIZE_32', 2051.00, 1558.76, 'NIKE', 'img/tshirt9.jpg', 'Nike India', 'Premium quality and comfortable fit.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (30, 'Nike T-Shirt 10', 'MEN', 'MEN', 'RED', 'SIZE_34', 2400.00, 1680.00, 'NIKE', 'img/tshirt10.jpg', 'Nike India', 'Trendy design with breathable fabric.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (31, 'Levis Jeans 1', 'MEN', 'MEN', 'NAVY', 'SIZE_30', 2167.00, 1625.25, 'LEVIS', 'img/jeans1.jpg', 'Levi's India', 'Trendy design with breathable fabric.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (32, 'Levis Jeans 2', 'MEN', 'MEN', 'BLACK', 'SIZE_34', 1030.00, 896.10, 'LEVIS', 'img/jeans2.jpg', 'Levi's India', 'Durable, lightweight, and perfect for all-day wear.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (33, 'Levis Jeans 3', 'MEN', 'MEN', 'BLACK', 'SIZE_34', 2004.00, 1583.16, 'LEVIS', 'img/jeans3.jpg', 'Levi's India', 'Durable, lightweight, and perfect for all-day wear.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (34, 'Levis Jeans 4', 'MEN', 'MEN', 'NAVY', 'SIZE_32', 2326.00, 1907.32, 'LEVIS', 'img/jeans4.jpg', 'Levi's India', 'Durable, lightweight, and perfect for all-day wear.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (35, 'Levis Jeans 5', 'MEN', 'MEN', 'BLACK', 'SIZE_34', 1735.00, 1266.55, 'LEVIS', 'img/jeans5.jpg', 'Levi's India', 'Trendy design with breathable fabric.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (36, 'Levis Jeans 6', 'MEN', 'MEN', 'GREEN', 'SIZE_42', 1538.00, 1107.36, 'LEVIS', 'img/jeans6.jpg', 'Levi's India', 'Premium quality and comfortable fit.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (37, 'Levis Jeans 7', 'MEN', 'MEN', 'GREEN', 'SIZE_32', 2173.00, 1651.48, 'LEVIS', 'img/jeans7.jpg', 'Levi's India', 'Durable, lightweight, and perfect for all-day wear.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (38, 'Levis Jeans 8', 'MEN', 'MEN', 'RED', 'SIZE_42', 1748.00, 1485.80, 'LEVIS', 'img/jeans8.jpg', 'Levi's India', 'Durable, lightweight, and perfect for all-day wear.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (39, 'Levis Jeans 9', 'MEN', 'MEN', 'BLUE', 'SIZE_38', 1566.00, 1362.42, 'LEVIS', 'img/jeans9.jpg', 'Levi's India', 'Durable, lightweight, and perfect for all-day wear.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (40, 'Levis Jeans 10', 'MEN', 'MEN', 'RED', 'SIZE_40', 2418.00, 2152.02, 'LEVIS', 'img/jeans10.jpg', 'Levi's India', 'Durable, lightweight, and perfect for all-day wear.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (41, 'Peter_England Trousers 1', 'MEN', 'MEN', 'MAROON', 'SIZE_38', 2151.00, 1742.31, 'PETER_ENGLAND', 'img/trousers1.jpg', 'Peter England India', 'Crafted with precision and stylish appeal.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (42, 'Peter_England Trousers 2', 'MEN', 'MEN', 'GREEN', 'SIZE_44', 2223.00, 1867.32, 'PETER_ENGLAND', 'img/trousers2.jpg', 'Peter England India', 'Perfect for casual and semi-formal wear.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (43, 'Peter_England Trousers 3', 'MEN', 'MEN', 'NAVY', 'SIZE_44', 1812.00, 1612.68, 'PETER_ENGLAND', 'img/trousers3.jpg', 'Peter England India', 'Trendy design with breathable fabric.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (44, 'Peter_England Trousers 4', 'MEN', 'MEN', 'RED', 'SIZE_44', 2207.00, 1544.90, 'PETER_ENGLAND', 'img/trousers4.jpg', 'Peter England India', 'Durable, lightweight, and perfect for all-day wear.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (45, 'Peter_England Trousers 5', 'MEN', 'MEN', 'BLACK', 'SIZE_34', 2659.00, 2260.15, 'PETER_ENGLAND', 'img/trousers5.jpg', 'Peter England India', 'Perfect for casual and semi-formal wear.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (46, 'Peter_England Trousers 6', 'MEN', 'MEN', 'BLUE', 'SIZE_36', 2052.00, 1662.12, 'PETER_ENGLAND', 'img/trousers6.jpg', 'Peter England India', 'Durable, lightweight, and perfect for all-day wear.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (47, 'Peter_England Trousers 7', 'MEN', 'MEN', 'BROWN', 'SIZE_42', 2660.00, 2021.60, 'PETER_ENGLAND', 'img/trousers7.jpg', 'Peter England India', 'Trendy design with breathable fabric.', 3.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (48, 'Peter_England Trousers 8', 'MEN', 'MEN', 'BLACK', 'SIZE_30', 1262.00, 896.02, 'PETER_ENGLAND', 'img/trousers8.jpg', 'Peter England India', 'Perfect for casual and semi-formal wear.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (49, 'Peter_England Trousers 9', 'MEN', 'MEN', 'GREY', 'SIZE_34', 2391.00, 1697.61, 'PETER_ENGLAND', 'img/trousers9.jpg', 'Peter England India', 'Perfect for casual and semi-formal wear.', 3.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (50, 'Peter_England Trousers 10', 'MEN', 'MEN', 'YELLOW', 'SIZE_30', 2902.00, 2321.60, 'PETER_ENGLAND', 'img/trousers10.jpg', 'Peter England India', 'Crafted with precision and stylish appeal.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (51, 'Adidas Shorts 1', 'MEN', 'MEN', 'BLACK', 'SIZE_30', 2182.00, 1963.80, 'ADIDAS', 'img/shorts1.jpg', 'Adidas India', 'Trendy design with breathable fabric.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (52, 'Adidas Shorts 2', 'MEN', 'MEN', 'NAVY', 'SIZE_42', 1203.00, 962.40, 'ADIDAS', 'img/shorts2.jpg', 'Adidas India', 'Trendy design with breathable fabric.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (53, 'Adidas Shorts 3', 'MEN', 'MEN', 'BLUE', 'SIZE_40', 2435.00, 2045.40, 'ADIDAS', 'img/shorts3.jpg', 'Adidas India', 'Perfect for casual and semi-formal wear.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (54, 'Adidas Shorts 4', 'MEN', 'MEN', 'BLACK', 'SIZE_34', 1433.00, 1218.05, 'ADIDAS', 'img/shorts4.jpg', 'Adidas India', 'Crafted with precision and stylish appeal.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (55, 'Adidas Shorts 5', 'MEN', 'MEN', 'BROWN', 'SIZE_40', 2565.00, 1846.80, 'ADIDAS', 'img/shorts5.jpg', 'Adidas India', 'Premium quality and comfortable fit.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (56, 'Adidas Shorts 6', 'MEN', 'MEN', 'YELLOW', 'SIZE_32', 1401.00, 1036.74, 'ADIDAS', 'img/shorts6.jpg', 'Adidas India', 'Trendy design with breathable fabric.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (57, 'Adidas Shorts 7', 'MEN', 'MEN', 'BROWN', 'SIZE_42', 1363.00, 1008.62, 'ADIDAS', 'img/shorts7.jpg', 'Adidas India', 'Perfect for casual and semi-formal wear.', 3.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (58, 'Adidas Shorts 8', 'MEN', 'MEN', 'YELLOW', 'SIZE_38', 1506.00, 1234.92, 'ADIDAS', 'img/shorts8.jpg', 'Adidas India', 'Crafted with precision and stylish appeal.', 3.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (59, 'Adidas Shorts 9', 'MEN', 'MEN', 'GREEN', 'SIZE_30', 2993.00, 2095.10, 'ADIDAS', 'img/shorts9.jpg', 'Adidas India', 'Perfect for casual and semi-formal wear.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (60, 'Adidas Shorts 10', 'MEN', 'MEN', 'YELLOW', 'SIZE_44', 2974.00, 2349.46, 'ADIDAS', 'img/shorts10.jpg', 'Adidas India', 'Durable, lightweight, and perfect for all-day wear.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (61, 'Puma Sweatshirt 1', 'MEN', 'MEN', 'BLUE', 'SIZE_36', 2255.00, 1939.30, 'PUMA', 'img/sweatshirt1.jpg', 'Puma India', 'Trendy design with breathable fabric.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (62, 'Puma Sweatshirt 2', 'MEN', 'MEN', 'NAVY', 'SIZE_42', 2135.00, 1579.90, 'PUMA', 'img/sweatshirt2.jpg', 'Puma India', 'Crafted with precision and stylish appeal.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (63, 'Puma Sweatshirt 3', 'MEN', 'MEN', 'BLUE', 'SIZE_34', 1554.00, 1212.12, 'PUMA', 'img/sweatshirt3.jpg', 'Puma India', 'Durable, lightweight, and perfect for all-day wear.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (64, 'Puma Sweatshirt 4', 'MEN', 'MEN', 'RED', 'SIZE_44', 2915.00, 2332.00, 'PUMA', 'img/sweatshirt4.jpg', 'Puma India', 'Crafted with precision and stylish appeal.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (65, 'Puma Sweatshirt 5', 'MEN', 'MEN', 'RED', 'SIZE_30', 2581.00, 1884.13, 'PUMA', 'img/sweatshirt5.jpg', 'Puma India', 'Crafted with precision and stylish appeal.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (66, 'Puma Sweatshirt 6', 'MEN', 'MEN', 'MAROON', 'SIZE_38', 1242.00, 1068.12, 'PUMA', 'img/sweatshirt6.jpg', 'Puma India', 'Premium quality and comfortable fit.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (67, 'Puma Sweatshirt 7', 'MEN', 'MEN', 'BROWN', 'SIZE_38', 2143.00, 1885.84, 'PUMA', 'img/sweatshirt7.jpg', 'Puma India', 'Durable, lightweight, and perfect for all-day wear.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (68, 'Puma Sweatshirt 8', 'MEN', 'MEN', 'YELLOW', 'SIZE_38', 1384.00, 1038.00, 'PUMA', 'img/sweatshirt8.jpg', 'Puma India', 'Durable, lightweight, and perfect for all-day wear.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (69, 'Puma Sweatshirt 9', 'MEN', 'MEN', 'NAVY', 'SIZE_40', 2420.00, 1839.20, 'PUMA', 'img/sweatshirt9.jpg', 'Puma India', 'Perfect for casual and semi-formal wear.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (70, 'Puma Sweatshirt 10', 'MEN', 'MEN', 'BLUE', 'SIZE_42', 1938.00, 1492.26, 'PUMA', 'img/sweatshirt10.jpg', 'Puma India', 'Premium quality and comfortable fit.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (71, 'Manyavar Kurta 1', 'MEN', 'MEN', 'YELLOW', 'SIZE_32', 2909.00, 2472.65, 'MANYAVAR', 'img/kurta1.jpg', 'Manyavar India', 'Durable, lightweight, and perfect for all-day wear.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (72, 'Manyavar Kurta 2', 'MEN', 'MEN', 'GREEN', 'SIZE_34', 2977.00, 2470.91, 'MANYAVAR', 'img/kurta2.jpg', 'Manyavar India', 'Durable, lightweight, and perfect for all-day wear.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (73, 'Manyavar Kurta 3', 'MEN', 'MEN', 'GREEN', 'SIZE_34', 1338.00, 990.12, 'MANYAVAR', 'img/kurta3.jpg', 'Manyavar India', 'Crafted with precision and stylish appeal.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (74, 'Manyavar Kurta 4', 'MEN', 'MEN', 'BLUE', 'SIZE_32', 1007.00, 795.53, 'MANYAVAR', 'img/kurta4.jpg', 'Manyavar India', 'Trendy design with breathable fabric.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (75, 'Manyavar Kurta 5', 'MEN', 'MEN', 'RED', 'SIZE_42', 1195.00, 979.90, 'MANYAVAR', 'img/kurta5.jpg', 'Manyavar India', 'Durable, lightweight, and perfect for all-day wear.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (76, 'Manyavar Kurta 6', 'MEN', 'MEN', 'NAVY', 'SIZE_32', 2951.00, 2655.90, 'MANYAVAR', 'img/kurta6.jpg', 'Manyavar India', 'Crafted with precision and stylish appeal.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (77, 'Manyavar Kurta 7', 'MEN', 'MEN', 'BROWN', 'SIZE_42', 2387.00, 1957.34, 'MANYAVAR', 'img/kurta7.jpg', 'Manyavar India', 'Crafted with precision and stylish appeal.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (78, 'Manyavar Kurta 8', 'MEN', 'MEN', 'BLACK', 'SIZE_30', 1003.00, 792.37, 'MANYAVAR', 'img/kurta8.jpg', 'Manyavar India', 'Premium quality and comfortable fit.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (79, 'Manyavar Kurta 9', 'MEN', 'MEN', 'NAVY', 'SIZE_42', 2292.00, 1696.08, 'MANYAVAR', 'img/kurta9.jpg', 'Manyavar India', 'Crafted with precision and stylish appeal.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (80, 'Manyavar Kurta 10', 'MEN', 'MEN', 'WHITE', 'SIZE_40', 2566.00, 1796.20, 'MANYAVAR', 'img/kurta10.jpg', 'Manyavar India', 'Premium quality and comfortable fit.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (81, 'Reebok Trackpants & Joggers 1', 'MEN', 'MEN', 'GREY', 'SIZE_40', 2833.00, 2209.74, 'REEBOK', 'img/trackpants1.jpg', 'Reebok India', 'Crafted with precision and stylish appeal.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (82, 'Reebok Trackpants & Joggers 2', 'MEN', 'MEN', 'RED', 'SIZE_42', 1672.00, 1304.16, 'REEBOK', 'img/trackpants2.jpg', 'Reebok India', 'Durable, lightweight, and perfect for all-day wear.', 3.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (83, 'Reebok Trackpants & Joggers 3', 'MEN', 'MEN', 'GREEN', 'SIZE_42', 1294.00, 1061.08, 'REEBOK', 'img/trackpants3.jpg', 'Reebok India', 'Premium quality and comfortable fit.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (84, 'Reebok Trackpants & Joggers 4', 'MEN', 'MEN', 'BROWN', 'SIZE_34', 1973.00, 1479.75, 'REEBOK', 'img/trackpants4.jpg', 'Reebok India', 'Trendy design with breathable fabric.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (85, 'Reebok Trackpants & Joggers 5', 'MEN', 'MEN', 'WHITE', 'SIZE_40', 1625.00, 1316.25, 'REEBOK', 'img/trackpants5.jpg', 'Reebok India', 'Crafted with precision and stylish appeal.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (86, 'Reebok Trackpants & Joggers 6', 'MEN', 'MEN', 'BLUE', 'SIZE_38', 1296.00, 1140.48, 'REEBOK', 'img/trackpants6.jpg', 'Reebok India', 'Trendy design with breathable fabric.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (87, 'Reebok Trackpants & Joggers 7', 'MEN', 'MEN', 'BROWN', 'SIZE_32', 1051.00, 893.35, 'REEBOK', 'img/trackpants7.jpg', 'Reebok India', 'Crafted with precision and stylish appeal.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (88, 'Reebok Trackpants & Joggers 8', 'MEN', 'MEN', 'NAVY', 'SIZE_34', 2171.00, 1736.80, 'REEBOK', 'img/trackpants8.jpg', 'Reebok India', 'Trendy design with breathable fabric.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (89, 'Reebok Trackpants & Joggers 9', 'MEN', 'MEN', 'GREY', 'SIZE_32', 1404.00, 1221.48, 'REEBOK', 'img/trackpants9.jpg', 'Reebok India', 'Premium quality and comfortable fit.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (90, 'Reebok Trackpants & Joggers 10', 'MEN', 'MEN', 'WHITE', 'SIZE_38', 1008.00, 796.32, 'REEBOK', 'img/trackpants10.jpg', 'Reebok India', 'Durable, lightweight, and perfect for all-day wear.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (91, 'Hrx Jacket 1', 'MEN', 'MEN', 'WHITE', 'SIZE_32', 1107.00, 963.09, 'HRX', 'img/jacket1.jpg', 'HRX India', 'Crafted with precision and stylish appeal.', 3.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (92, 'Hrx Jacket 2', 'MEN', 'MEN', 'GREEN', 'SIZE_34', 1478.00, 1167.62, 'HRX', 'img/jacket2.jpg', 'HRX India', 'Durable, lightweight, and perfect for all-day wear.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (93, 'Hrx Jacket 3', 'MEN', 'MEN', 'WHITE', 'SIZE_32', 2127.00, 1829.22, 'HRX', 'img/jacket3.jpg', 'HRX India', 'Premium quality and comfortable fit.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (94, 'Hrx Jacket 4', 'MEN', 'MEN', 'BLUE', 'SIZE_40', 1886.00, 1508.80, 'HRX', 'img/jacket4.jpg', 'HRX India', 'Durable, lightweight, and perfect for all-day wear.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (95, 'Hrx Jacket 5', 'MEN', 'MEN', 'GREY', 'SIZE_34', 1446.00, 1171.26, 'HRX', 'img/jacket5.jpg', 'HRX India', 'Crafted with precision and stylish appeal.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (96, 'Hrx Jacket 6', 'MEN', 'MEN', 'BLACK', 'SIZE_36', 2331.00, 1678.32, 'HRX', 'img/jacket6.jpg', 'HRX India', 'Crafted with precision and stylish appeal.', 3.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (97, 'Hrx Jacket 7', 'MEN', 'MEN', 'GREY', 'SIZE_44', 1742.00, 1567.80, 'HRX', 'img/jacket7.jpg', 'HRX India', 'Crafted with precision and stylish appeal.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (98, 'Hrx Jacket 8', 'MEN', 'MEN', 'GREY', 'SIZE_38', 2793.00, 2290.26, 'HRX', 'img/jacket8.jpg', 'HRX India', 'Premium quality and comfortable fit.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (99, 'Hrx Jacket 9', 'MEN', 'MEN', 'MAROON', 'SIZE_32', 2976.00, 2291.52, 'HRX', 'img/jacket9.jpg', 'HRX India', 'Crafted with precision and stylish appeal.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (100, 'Hrx Jacket 10', 'MEN', 'MEN', 'YELLOW', 'SIZE_40', 2536.00, 2079.52, 'HRX', 'img/jacket10.jpg', 'HRX India', 'Perfect for casual and semi-formal wear.', 4.5);



-- WOMEN DATA *******************************************************************************************************************************************************************************************************************************************************************



INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (101, 'Biba Kurti 1', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_32', 1267.00, 1127.63, 'BIBA', 'img/women_kurti1.jpg', 'Biba India', 'Perfect for casual and semi-formal wear.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (102, 'Biba Kurti 2', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_40', 1489.00, 1072.08, 'BIBA', 'img/women_kurti2.jpg', 'Biba India', 'Premium quality and comfortable fit.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (103, 'Biba Kurti 3', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_40', 1312.00, 905.28, 'BIBA', 'img/women_kurti3.jpg', 'Biba India', 'Premium quality and comfortable fit.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (104, 'Biba Kurti 4', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_32', 2748.00, 2143.44, 'BIBA', 'img/women_kurti4.jpg', 'Biba India', 'Crafted with precision and stylish appeal.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (105, 'Biba Kurti 5', 'WOMEN', 'WOMEN', 'RED', 'SIZE_42', 2880.00, 2044.80, 'BIBA', 'img/women_kurti5.jpg', 'Biba India', 'Durable, lightweight, and perfect for all-day wear.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (106, 'Biba Kurti 6', 'WOMEN', 'WOMEN', 'MAROON', 'SIZE_32', 1956.00, 1427.88, 'BIBA', 'img/women_kurti6.jpg', 'Biba India', 'Durable, lightweight, and perfect for all-day wear.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (107, 'Biba Kurti 7', 'WOMEN', 'WOMEN', 'GREY', 'SIZE_44', 2916.00, 2157.84, 'BIBA', 'img/women_kurti7.jpg', 'Biba India', 'Premium quality and comfortable fit.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (108, 'Biba Kurti 8', 'WOMEN', 'WOMEN', 'YELLOW', 'SIZE_30', 2329.00, 1653.59, 'BIBA', 'img/women_kurti8.jpg', 'Biba India', 'Perfect for casual and semi-formal wear.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (109, 'Biba Kurti 9', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_34', 2731.00, 1884.39, 'BIBA', 'img/women_kurti9.jpg', 'Biba India', 'Perfect for casual and semi-formal wear.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (110, 'Biba Kurti 10', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_44', 2693.00, 2208.26, 'BIBA', 'img/women_kurti10.jpg', 'Biba India', 'Crafted with precision and stylish appeal.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (111, 'Only Top & Tunic 1', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_32', 1867.00, 1549.61, 'ONLY', 'img/women_top1.jpg', 'Only India', 'Crafted with precision and stylish appeal.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (112, 'Only Top & Tunic 2', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_30', 1934.00, 1276.44, 'ONLY', 'img/women_top2.jpg', 'Only India', 'Crafted with precision and stylish appeal.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (113, 'Only Top & Tunic 3', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_44', 2695.00, 1967.35, 'ONLY', 'img/women_top3.jpg', 'Only India', 'Perfect for casual and semi-formal wear.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (114, 'Only Top & Tunic 4', 'WOMEN', 'WOMEN', 'YELLOW', 'SIZE_38', 2200.00, 1826.00, 'ONLY', 'img/women_top4.jpg', 'Only India', 'Crafted with precision and stylish appeal.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (115, 'Only Top & Tunic 5', 'WOMEN', 'WOMEN', 'MAROON', 'SIZE_44', 2369.00, 1776.75, 'ONLY', 'img/women_top5.jpg', 'Only India', 'Durable, lightweight, and perfect for all-day wear.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (116, 'Only Top & Tunic 6', 'WOMEN', 'WOMEN', 'WHITE', 'SIZE_30', 2272.00, 1772.16, 'ONLY', 'img/women_top6.jpg', 'Only India', 'Crafted with precision and stylish appeal.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (117, 'Only Top & Tunic 7', 'WOMEN', 'WOMEN', 'YELLOW', 'SIZE_36', 1191.00, 809.88, 'ONLY', 'img/women_top7.jpg', 'Only India', 'Crafted with precision and stylish appeal.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (118, 'Only Top & Tunic 8', 'WOMEN', 'WOMEN', 'RED', 'SIZE_44', 1592.00, 1241.76, 'ONLY', 'img/women_top8.jpg', 'Only India', 'Durable, lightweight, and perfect for all-day wear.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (119, 'Only Top & Tunic 9', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_36', 2440.00, 2196.00, 'ONLY', 'img/women_top9.jpg', 'Only India', 'Perfect for casual and semi-formal wear.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (120, 'Only Top & Tunic 10', 'WOMEN', 'WOMEN', 'WHITE', 'SIZE_38', 1396.00, 1060.96, 'ONLY', 'img/women_top10.jpg', 'Only India', 'Durable, lightweight, and perfect for all-day wear.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (121, 'Levis Jeans 1', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_42', 1765.00, 1323.75, 'LEVIS', 'img/women_jeans1.jpg', 'Levi's India', 'Premium quality and comfortable fit.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (122, 'Levis Jeans 2', 'WOMEN', 'WOMEN', 'RED', 'SIZE_36', 1747.00, 1502.42, 'LEVIS', 'img/women_jeans2.jpg', 'Levi's India', 'Durable, lightweight, and perfect for all-day wear.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (123, 'Levis Jeans 3', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_34', 1449.00, 1289.61, 'LEVIS', 'img/women_jeans3.jpg', 'Levi's India', 'Trendy design with breathable fabric.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (124, 'Levis Jeans 4', 'WOMEN', 'WOMEN', 'GREY', 'SIZE_34', 1195.00, 956.00, 'LEVIS', 'img/women_jeans4.jpg', 'Levi's India', 'Trendy design with breathable fabric.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (125, 'Levis Jeans 5', 'WOMEN', 'WOMEN', 'YELLOW', 'SIZE_30', 1867.00, 1624.29, 'LEVIS', 'img/women_jeans5.jpg', 'Levi's India', 'Crafted with precision and stylish appeal.', 3.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (126, 'Levis Jeans 6', 'WOMEN', 'WOMEN', 'YELLOW', 'SIZE_40', 1937.00, 1317.16, 'LEVIS', 'img/women_jeans6.jpg', 'Levi's India', 'Trendy design with breathable fabric.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (127, 'Levis Jeans 7', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_44', 2900.00, 2610.00, 'LEVIS', 'img/women_jeans7.jpg', 'Levi's India', 'Premium quality and comfortable fit.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (128, 'Levis Jeans 8', 'WOMEN', 'WOMEN', 'WHITE', 'SIZE_36', 2144.00, 1629.44, 'LEVIS', 'img/women_jeans8.jpg', 'Levi's India', 'Premium quality and comfortable fit.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (129, 'Levis Jeans 9', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_38', 2094.00, 1549.56, 'LEVIS', 'img/women_jeans9.jpg', 'Levi's India', 'Premium quality and comfortable fit.', 3.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (130, 'Levis Jeans 10', 'WOMEN', 'WOMEN', 'WHITE', 'SIZE_30', 2198.00, 1846.32, 'LEVIS', 'img/women_jeans10.jpg', 'Levi's India', 'Crafted with precision and stylish appeal.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (131, 'Zara Trousers 1', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_40', 1747.00, 1345.19, 'ZARA', 'img/women_trousers1.jpg', 'Zara India', 'Trendy design with breathable fabric.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (132, 'Zara Trousers 2', 'WOMEN', 'WOMEN', 'WHITE', 'SIZE_36', 3006.00, 2284.56, 'ZARA', 'img/women_trousers2.jpg', 'Zara India', 'Crafted with precision and stylish appeal.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (133, 'Zara Trousers 3', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_30', 2178.00, 1677.06, 'ZARA', 'img/women_trousers3.jpg', 'Zara India', 'Perfect for casual and semi-formal wear.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (134, 'Zara Trousers 4', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_38', 2185.00, 1529.50, 'ZARA', 'img/women_trousers4.jpg', 'Zara India', 'Trendy design with breathable fabric.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (135, 'Zara Trousers 5', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_42', 1771.00, 1239.70, 'ZARA', 'img/women_trousers5.jpg', 'Zara India', 'Perfect for casual and semi-formal wear.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (136, 'Zara Trousers 6', 'WOMEN', 'WOMEN', 'GREY', 'SIZE_44', 2859.00, 2344.38, 'ZARA', 'img/women_trousers6.jpg', 'Zara India', 'Premium quality and comfortable fit.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (137, 'Zara Trousers 7', 'WOMEN', 'WOMEN', 'NAVY', 'SIZE_44', 1129.00, 914.49, 'ZARA', 'img/women_trousers7.jpg', 'Zara India', 'Perfect for casual and semi-formal wear.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (138, 'Zara Trousers 8', 'WOMEN', 'WOMEN', 'RED', 'SIZE_44', 1519.00, 1291.15, 'ZARA', 'img/women_trousers8.jpg', 'Zara India', 'Premium quality and comfortable fit.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (139, 'Zara Trousers 9', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_36', 1673.00, 1187.83, 'ZARA', 'img/women_trousers9.jpg', 'Zara India', 'Perfect for casual and semi-formal wear.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (140, 'Zara Trousers 10', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_34', 1933.00, 1430.42, 'ZARA', 'img/women_trousers10.jpg', 'Zara India', 'Durable, lightweight, and perfect for all-day wear.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (141, 'And Dress 1', 'WOMEN', 'WOMEN', 'MAROON', 'SIZE_40', 1138.00, 830.74, 'AND', 'img/women_dress1.jpg', 'AND India', 'Perfect for casual and semi-formal wear.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (142, 'And Dress 2', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_42', 2453.00, 2109.58, 'AND', 'img/women_dress2.jpg', 'AND India', 'Premium quality and comfortable fit.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (143, 'And Dress 3', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_42', 2385.00, 2003.40, 'AND', 'img/women_dress3.jpg', 'AND India', 'Trendy design with breathable fabric.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (144, 'And Dress 4', 'WOMEN', 'WOMEN', 'GREY', 'SIZE_42', 2521.00, 1991.59, 'AND', 'img/women_dress4.jpg', 'AND India', 'Perfect for casual and semi-formal wear.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (145, 'And Dress 5', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_40', 2588.00, 1708.08, 'AND', 'img/women_dress5.jpg', 'AND India', 'Perfect for casual and semi-formal wear.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (146, 'And Dress 6', 'WOMEN', 'WOMEN', 'WHITE', 'SIZE_40', 1172.00, 855.56, 'AND', 'img/women_dress6.jpg', 'AND India', 'Durable, lightweight, and perfect for all-day wear.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (147, 'And Dress 7', 'WOMEN', 'WOMEN', 'WHITE', 'SIZE_38', 2048.00, 1761.28, 'AND', 'img/women_dress7.jpg', 'AND India', 'Trendy design with breathable fabric.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (148, 'And Dress 8', 'WOMEN', 'WOMEN', 'MAROON', 'SIZE_40', 2927.00, 2312.33, 'AND', 'img/women_dress8.jpg', 'AND India', 'Crafted with precision and stylish appeal.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (149, 'And Dress 9', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_42', 3166.00, 2532.80, 'AND', 'img/women_dress9.jpg', 'AND India', 'Premium quality and comfortable fit.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (150, 'And Dress 10', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_44', 3020.00, 2295.20, 'AND', 'img/women_dress10.jpg', 'AND India', 'Durable, lightweight, and perfect for all-day wear.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (151, 'Fabindia Saree 1', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_40', 2643.00, 2193.69, 'FABINDIA', 'img/women_saree1.jpg', 'Fabindia', 'Premium quality and comfortable fit.', 5.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (152, 'Fabindia Saree 2', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_42', 2282.00, 1688.68, 'FABINDIA', 'img/women_saree2.jpg', 'Fabindia', 'Trendy design with breathable fabric.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (153, 'Fabindia Saree 3', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_42', 1337.00, 1002.75, 'FABINDIA', 'img/women_saree3.jpg', 'Fabindia', 'Perfect for casual and semi-formal wear.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (154, 'Fabindia Saree 4', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_40', 1655.00, 1158.50, 'FABINDIA', 'img/women_saree4.jpg', 'Fabindia', 'Perfect for casual and semi-formal wear.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (155, 'Fabindia Saree 5', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_34', 2323.00, 1765.48, 'FABINDIA', 'img/women_saree5.jpg', 'Fabindia', 'Perfect for casual and semi-formal wear.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (156, 'Fabindia Saree 6', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_32', 2834.00, 2012.14, 'FABINDIA', 'img/women_saree6.jpg', 'Fabindia', 'Durable, lightweight, and perfect for all-day wear.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (157, 'Fabindia Saree 7', 'WOMEN', 'WOMEN', 'MAROON', 'SIZE_36', 2479.00, 1884.04, 'FABINDIA', 'img/women_saree7.jpg', 'Fabindia', 'Trendy design with breathable fabric.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (158, 'Fabindia Saree 8', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_32', 1470.00, 1131.90, 'FABINDIA', 'img/women_saree8.jpg', 'Fabindia', 'Premium quality and comfortable fit.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (159, 'Fabindia Saree 9', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_42', 3154.00, 2523.20, 'FABINDIA', 'img/women_saree9.jpg', 'Fabindia', 'Durable, lightweight, and perfect for all-day wear.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (160, 'Fabindia Saree 10', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_32', 1973.00, 1460.02, 'FABINDIA', 'img/women_saree10.jpg', 'Fabindia', 'Trendy design with breathable fabric.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (161, 'Vero_Moda Skirt 1', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_32', 1229.00, 1032.36, 'VERO_MODA', 'img/women_skirt1.jpg', 'Vero Moda India', 'Perfect for casual and semi-formal wear.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (162, 'Vero_Moda Skirt 2', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_34', 1750.00, 1435.00, 'VERO_MODA', 'img/women_skirt2.jpg', 'Vero Moda India', 'Trendy design with breathable fabric.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (163, 'Vero_Moda Skirt 3', 'WOMEN', 'WOMEN', 'NAVY', 'SIZE_34', 1269.00, 1065.96, 'VERO_MODA', 'img/women_skirt3.jpg', 'Vero Moda India', 'Durable, lightweight, and perfect for all-day wear.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (164, 'Vero_Moda Skirt 4', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_42', 1613.00, 1177.49, 'VERO_MODA', 'img/women_skirt4.jpg', 'Vero Moda India', 'Crafted with precision and stylish appeal.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (165, 'Vero_Moda Skirt 5', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_40', 2565.00, 1821.15, 'VERO_MODA', 'img/women_skirt5.jpg', 'Vero Moda India', 'Premium quality and comfortable fit.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (166, 'Vero_Moda Skirt 6', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_32', 1427.00, 1212.95, 'VERO_MODA', 'img/women_skirt6.jpg', 'Vero Moda India', 'Trendy design with breathable fabric.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (167, 'Vero_Moda Skirt 7', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_38', 2769.00, 1855.23, 'VERO_MODA', 'img/women_skirt7.jpg', 'Vero Moda India', 'Crafted with precision and stylish appeal.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (168, 'Vero_Moda Skirt 8', 'WOMEN', 'WOMEN', 'GREY', 'SIZE_36', 1333.00, 1013.08, 'VERO_MODA', 'img/women_skirt8.jpg', 'Vero Moda India', 'Durable, lightweight, and perfect for all-day wear.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (169, 'Vero_Moda Skirt 9', 'WOMEN', 'WOMEN', 'NAVY', 'SIZE_40', 3055.00, 2657.85, 'VERO_MODA', 'img/women_skirt9.jpg', 'Vero Moda India', 'Perfect for casual and semi-formal wear.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (170, 'Vero_Moda Skirt 10', 'WOMEN', 'WOMEN', 'GREY', 'SIZE_42', 2125.00, 1721.25, 'VERO_MODA', 'img/women_skirt10.jpg', 'Vero Moda India', 'Crafted with precision and stylish appeal.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (171, 'H&M Jacket 1', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_42', 2366.00, 1561.56, 'H&M', 'img/women_jacket1.jpg', 'H&M India', 'Trendy design with breathable fabric.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (172, 'H&M Jacket 2', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_36', 3140.00, 2449.20, 'H&M', 'img/women_jacket2.jpg', 'H&M India', 'Premium quality and comfortable fit.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (173, 'H&M Jacket 3', 'WOMEN', 'WOMEN', 'MAROON', 'SIZE_32', 1849.00, 1275.81, 'H&M', 'img/women_jacket3.jpg', 'H&M India', 'Perfect for casual and semi-formal wear.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (174, 'H&M Jacket 4', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_34', 2745.00, 1866.60, 'H&M', 'img/women_jacket4.jpg', 'H&M India', 'Premium quality and comfortable fit.', 3.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (175, 'H&M Jacket 5', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_32', 1225.00, 1029.00, 'H&M', 'img/women_jacket5.jpg', 'H&M India', 'Premium quality and comfortable fit.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (176, 'H&M Jacket 6', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_34', 1617.00, 1131.90, 'H&M', 'img/women_jacket6.jpg', 'H&M India', 'Durable, lightweight, and perfect for all-day wear.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (177, 'H&M Jacket 7', 'WOMEN', 'WOMEN', 'MAROON', 'SIZE_42', 2227.00, 1670.25, 'H&M', 'img/women_jacket7.jpg', 'H&M India', 'Perfect for casual and semi-formal wear.', 3.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (178, 'H&M Jacket 8', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_38', 1651.00, 1452.88, 'H&M', 'img/women_jacket8.jpg', 'H&M India', 'Trendy design with breathable fabric.', 4.3);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (179, 'H&M Jacket 9', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_40', 2031.00, 1462.32, 'H&M', 'img/women_jacket9.jpg', 'H&M India', 'Perfect for casual and semi-formal wear.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (180, 'H&M Jacket 10', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_40', 1146.00, 802.20, 'H&M', 'img/women_jacket10.jpg', 'H&M India', 'Crafted with precision and stylish appeal.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (181, 'F21 Co-ord 1', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_44', 2616.00, 2302.08, 'F21', 'img/women_coord1.jpg', 'Forever 21 India', 'Durable, lightweight, and perfect for all-day wear.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (182, 'F21 Co-ord 2', 'WOMEN', 'WOMEN', 'YELLOW', 'SIZE_30', 2560.00, 2304.00, 'F21', 'img/women_coord2.jpg', 'Forever 21 India', 'Trendy design with breathable fabric.', 4.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (183, 'F21 Co-ord 3', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_44', 2993.00, 2274.68, 'F21', 'img/women_coord3.jpg', 'Forever 21 India', 'Premium quality and comfortable fit.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (184, 'F21 Co-ord 4', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_30', 1421.00, 1222.06, 'F21', 'img/women_coord4.jpg', 'Forever 21 India', 'Perfect for casual and semi-formal wear.', 4.1);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (185, 'F21 Co-ord 5', 'WOMEN', 'WOMEN', 'NAVY', 'SIZE_36', 2621.00, 2149.22, 'F21', 'img/women_coord5.jpg', 'Forever 21 India', 'Premium quality and comfortable fit.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (186, 'F21 Co-ord 6', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_44', 2848.00, 2192.96, 'F21', 'img/women_coord6.jpg', 'Forever 21 India', 'Perfect for casual and semi-formal wear.', 4.7);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (187, 'F21 Co-ord 7', 'WOMEN', 'WOMEN', 'WHITE', 'SIZE_36', 1187.00, 937.73, 'F21', 'img/women_coord7.jpg', 'Forever 21 India', 'Crafted with precision and stylish appeal.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (188, 'F21 Co-ord 8', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_30', 1860.00, 1488.00, 'F21', 'img/women_coord8.jpg', 'Forever 21 India', 'Perfect for casual and semi-formal wear.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (189, 'F21 Co-ord 9', 'WOMEN', 'WOMEN', 'NAVY', 'SIZE_36', 2455.00, 2062.20, 'F21', 'img/women_coord9.jpg', 'Forever 21 India', 'Durable, lightweight, and perfect for all-day wear.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (190, 'F21 Co-ord 10', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_30', 1681.00, 1277.56, 'F21', 'img/women_coord10.jpg', 'Forever 21 India', 'Durable, lightweight, and perfect for all-day wear.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (191, 'Mango Jumpsuit 1', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_30', 3048.00, 2255.52, 'MANGO', 'img/women_jumpsuit1.jpg', 'Mango India', 'Crafted with precision and stylish appeal.', 4.4);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (192, 'Mango Jumpsuit 2', 'WOMEN', 'WOMEN', 'GREEN', 'SIZE_34', 1949.00, 1266.85, 'MANGO', 'img/women_jumpsuit2.jpg', 'Mango India', 'Premium quality and comfortable fit.', 3.6);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (193, 'Mango Jumpsuit 3', 'WOMEN', 'WOMEN', 'WHITE', 'SIZE_40', 2469.00, 1678.92, 'MANGO', 'img/women_jumpsuit3.jpg', 'Mango India', 'Durable, lightweight, and perfect for all-day wear.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (194, 'Mango Jumpsuit 4', 'WOMEN', 'WOMEN', 'RED', 'SIZE_32', 1372.00, 1097.60, 'MANGO', 'img/women_jumpsuit4.jpg', 'Mango India', 'Premium quality and comfortable fit.', 4.0);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (195, 'Mango Jumpsuit 5', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_40', 2545.00, 2112.35, 'MANGO', 'img/women_jumpsuit5.jpg', 'Mango India', 'Durable, lightweight, and perfect for all-day wear.', 4.9);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (196, 'Mango Jumpsuit 6', 'WOMEN', 'WOMEN', 'YELLOW', 'SIZE_36', 2883.00, 2219.91, 'MANGO', 'img/women_jumpsuit6.jpg', 'Mango India', 'Trendy design with breathable fabric.', 4.2);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (197, 'Mango Jumpsuit 7', 'WOMEN', 'WOMEN', 'BLACK', 'SIZE_34', 2291.00, 1924.44, 'MANGO', 'img/women_jumpsuit7.jpg', 'Mango India', 'Trendy design with breathable fabric.', 4.5);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (198, 'Mango Jumpsuit 8', 'WOMEN', 'WOMEN', 'NAVY', 'SIZE_42', 2810.00, 2248.00, 'MANGO', 'img/women_jumpsuit8.jpg', 'Mango India', 'Premium quality and comfortable fit.', 4.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (199, 'Mango Jumpsuit 9', 'WOMEN', 'WOMEN', 'BLUE', 'SIZE_32', 2209.00, 1833.47, 'MANGO', 'img/women_jumpsuit9.jpg', 'Mango India', 'Perfect for casual and semi-formal wear.', 3.8);
INSERT INTO product (id, name, category, ideal_for, color, size, price, discount_price, brand, image, seller, description, ratings) VALUES (200, 'Mango Jumpsuit 10', 'WOMEN', 'WOMEN', 'BROWN', 'SIZE_38', 2412.00, 2146.68, 'MANGO', 'img/women_jumpsuit10.jpg', 'Mango India', 'Durable, lightweight, and perfect for all-day wear.', 3.8);



-- *******************************************************************************************************************************************************************************************************************************************************************





















